#!/usr/bin/env perl

BEGIN {

    if ((exists $ENV{MUTATE_HOME}) and (-d $ENV{MUTATE_HOME})) {
        mkdir '/tmp/.mutate/' unless -e '/tmp/.mutate/';
        mkdir '/tmp/.mutate/tasks/' unless -e '/tmp/.mutate/tasks/';
    }
    else {
        die
          "You must set MUTATE_HOME to the directory where Mutate is located.\n";
    }
};

use 5.018_000;
use strict;
use warnings;

no if $] >= 5.018, warnings => "experimental::smartmatch";
no if $] >= 5.018, warnings => "experimental::lexical_subs";

unless (-e '/tmp/.mutate/mdaemon.pid')
{

    $ENV{MOJO_HOME} = $ENV{MUTATE_HOME};
    $ENV{MOJO_MAX_MESSAGE_SIZE} = 1000000000000;

    system
      "hypnotoad $ENV{MUTATE_HOME}/mdaemon";
}

exit(0);
