#!/usr/bin/env perl

BEGIN {

    unless ((exists $ENV{MUTATE_HOME}) and (-d $ENV{MUTATE_HOME})) {
        die
          "You must set MUTATE_HOME to the directory where Mutate is located.\n";
    }
}

use 5.010_000;
use strict;
use warnings;

use IO::File;
use DateTime;

use Mojolicious::Lite;
use Mojo::JSON;

plugin 'JSONConfig' => {file => "$ENV{MUTATE_HOME}/presets/mdaemon.settings"};


get '/' => sub { my $self = shift; };

get '/:command' => sub {

    my $self = shift;

    my $tx = $self->req->json;

    my $command = $self->param('command');

    my $task_file =
      IO::File->new("/tmp/.mutate/tasks/$command." . DateTime->now . "", "w");

    open my $shell, "$ENV{MUTATE_HOME}/$command $tx->{arguments} |";

    my @output;

    for (<$shell>) {
        push @output, $_;
    }
    close $shell;

    if (defined $task_file) {
        print $task_file "@output";
        undef $task_file;
    }

    return $self->render(text => "@output");

};

app->start;
