#!/usr/bin/env perl

BEGIN {

    unless ((exists $ENV{MUTATE_HOME}) and (-d $ENV{MUTATE_HOME})) {
        die
          "You must set MUTATE_HOME to the directory where Mutate is located.\n";
    }
}

use 5.018_000;
use strict;
use warnings;

no if $] >= 5.018, warnings => "experimental::smartmatch";
no if $] >= 5.018, warnings => "experimental::lexical_subs";

use IO::File;
use DateTime;

use Mojolicious::Lite;
use IO::Async::Loop::Mojo;

plugin 'JSONConfig' => {file => "$ENV{MUTATE_HOME}/presets/mdaemon.settings"};

our $LOOP = IO::Async::Loop::Mojo->new();

get '/' => sub { my $self = shift; };

get '/:command' => sub {

    my $self = shift;

    my $tx = $self->req->json;

    my $command = $self->param('command');

    my $event =
      IO::File->new("/tmp/.mutate/events/$command." . DateTime->now . "", "w");

    $LOOP->add(

        open my $shell, "$ENV{MUTATE_HOME}/$command $tx->{arguments} |";

            my @output;

            for (<$shell>) {
                push @output, chomp $_;
            }
            close $shell;

            if (defined $event) {
                print $event "@output";
                undef $event;
            }
        );
    };

app->start;
