#!/usr/bin/env perl

BEGIN {

    unless ((exists $ENV{MUTATE_HOME}) and (-d $ENV{MUTATE_HOME})) {
        die
          "You must set MUTATE_HOME to the directory where Mutate is located.\n";
    }
}

use 5.018_000;
use strict;
use warnings;

no if $] >= 5.018, warnings => "experimental::smartmatch";
no if $] >= 5.018, warnings => "experimental::lexical_subs";

use IO::File;
use DateTime;

use Mojolicious::Lite;
use Mojo::JSON;
use Mojo::IOLoop;

plugin 'JSONConfig' => {file => "$ENV{MUTATE_HOME}/presets/mdaemon.settings"};


get '/' => sub { my $self = shift; };

get '/:command' => sub {

    my $self = shift;

    my $tx = $self->req->json;

    my $command = $self->param('command');

    my $tasks =
      IO::File->new("/tmp/.mutate/tasks/$command." . DateTime->now . "", "w");

    open my $shell, "$ENV{MUTATE_HOME}/$command $tx->{arguments} |";

    my @output;

    for (<$shell>) {
        push @output, chomp $_;
    }
    close $shell;

    if (defined $tasks) {
        print $tasks "@output";
        undef $tasks;
    }

    return $self->render(json => @output);

};

app->start;
