#!/usr/bin/env perl

BEGIN {

    if ((exists $ENV{MUTATE_HOME}) and (-d $ENV{MUTATE_HOME})) {
        system "$ENV{MUTATE_HOME}/mbootstrap";
    }
    else {
        die
          "You must set MUTATE_HOME to the directory where Mutate is located.\n";
    }
}

use 5.010_000;
use strict;
use warnings;

use Getopt::Long qw/:config no_ignore_case /;
use Pod::Usage;


my %obj;

GetOptions(

    'help|?|h' => \$obj{options}->{'help'},
    'command|c' => \$obj{options}->{'command'},

);

pod2usage "\nmsubmit, High Performance A/V Encoding\n"
  if defined $obj{options}->{help}
  or not $ARGV[0];

unless (defined $obj{options}->{command})
{
    $obj{options}->{command} = 'mwriter';
}

use Mojo::UserAgent;

my $ua = Mojo::UserAgent->new;
my $tx = $ua->get("https://localhost:8443/$obj{options}->{command}" => {DNT => 1} => json => {arguments => "@ARGV"});

say $tx->res->body;

exit(0);

__END__

=head1 SYNOPSIS

<command> [options]

Options:

    -h, -?, --help  This help / usage screen...
    -c, --command   Commands: mreader, mwriter, mpresets

Example: msubmit -c mreader ~/Video

=cut
